##
# github actions to bench the experimental workstealing http2 connection pool
# (see https://github.com/reactor/reactor-pool/pull/179, https://github.com/reactor/reactor-netty/pull/2986)
#
# This workflow does the following:
#
# - it first build the two PRs #179 and #2986 and pushes it into local M2
# - then it builds frontend-rn-h2concurrent specific application which enables HTTP/2 work stealing pool
# - finally, it reuses the backend-rn-11x backend which is left unchanged
##
name: benchmarks-h2-concurrent-pool

on:
#  schedule:
#    - cron: '5 0 * * *'
  workflow_dispatch:
    inputs:
      simulations:
        description: 'Simulations for Reactor Netty 11x using http2 concurrent pools:'
        required: false
        type: string
        default: 'Remote'
      duration:
        description: 'Test duration (in seconds):'
        required: false
        type: string
        default: '60'
      alert-threshold:
        description: 'Alert threshold like "150%". Percentage indicating how worse the current benchmark result is, e.g: 150% means that an alert happens when current benchmark result is 1.5x worse than previous:'
        required: false
        type: string
        default: '125%'
      force-bench:
        type: boolean
        description: Forces benchmark even if there's no changes
        default: true
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'main'
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Checkout Reactor Pool PR
        uses: actions/checkout@v3
        with:
          repository: pderop/reactor-pool
          ref: 'workstealing-pool'
          path: reactor-pool-repo
          fetch-depth: 0

      - name: Checkout Reactor Netty PR
        uses: actions/checkout@v3
        with:
          repository: pderop/reactor-netty
          ref: 'workstealing-pool'
          path: reactor-netty-repo
          fetch-depth: 0

      - name: Compile Reactor Pool PR
        run: ./gradlew -x javadoc publishToMavenLocal
        working-directory: ./reactor-pool-repo

      - name: Compile Reactor Netty PR
        working-directory: ./reactor-netty-repo
        run: |-
          OLD_GITHUB_ACTION=$GITHUB_ACTION
          unset GITHUB_ACTION
          ./gradlew -x javadoc -x generateObservabilityDocs publishToMavenLocal
          export GITHUB_ACTION=$OLD_GITHUB_ACTION

      - name: Compile Frontend
        run: ./gradlew frontend-rn-h2concurrent:build

      - name: Compile Backend
        run: ./gradlew backend-rn-11x:build

      - name: Upload frontend
        uses: actions/upload-artifact@v4
        with:
          name: frontend-rn-h2concurrent-1.0.0
          path: frontend-rn-h2concurrent/build/libs/frontend-rn-h2concurrent-1.0.0.jar
          retention-days: 1
          if-no-files-found: error

      - name: Upload backend
        uses: actions/upload-artifact@v4
        with:
          name: backend-rn-11x-1.0.0
          path: backend-rn-11x/build/libs/backend-rn-11x-1.0.0.jar
          retention-days: 1
          if-no-files-found: error

  run-benchmarks:
    needs: build
    uses: ./.github/workflows/_benchmarks.yml
    secrets: inherit
    permissions:
      contents: write
    with:
      appname: benchmark-rn-concurrent-H2
      protocol: H2
      frontend-app: frontend-rn-h2concurrent-1.0.0
      backend-app: backend-rn-11x-1.0.0
      simulations: ${{ inputs.simulations || 'Remote' }}
      duration: ${{ inputs.duration || '60' }}
      alert-threshold: ${{ inputs.alert-threshold || '125%' }}
      force-bench: ${{ inputs.force-bench || false }}
      dependencies: |
        pderop;reactor-pool;workstealing-pool
        pderop;reactor-netty;workstealing-pool

  # Once all benchmarks are done, rebuild final shootout board README file
  update-readme:
    uses: ./.github/workflows/_update-readme.yml
    needs: [ run-benchmarks ]
    secrets: inherit
    permissions:
      contents: write
