##
# github actions to manually force GCP full cleanup (destroy VMs, buckets)
##
name: cleanup-gcp

on:
  workflow_dispatch:

jobs:
  benchmark-cleanup:
    uses: ./.github/workflows/_cleanup.yml
    secrets: inherit
