##
# github actions to manually deploy GCP VMs for gatling/frontend/backend
##
name: deploy-vm

on:
  workflow_dispatch:

jobs:
  benchmark-deploy-debug:
    uses: ./.github/workflows/_deploy-vm.yml
    secrets: inherit
    with:
      client-vm: benchmark-gatling
      frontend-vm: benchmark-frontend
      backend-vm: benchmark-backend
